@MyApp.API_HostAddress = http://localhost:5174

GET {{MyApp.API_HostAddress}}/api/Student/GetAllStudents/
Accept: application/json

###
POST {{MyApp.API_HostAddress}}/api/Student/AddStudent/
Accept: application/json
Content-Type: application/json
{
    "Name": "Marie Doe",
    "Class": "BCA",
    "FatherName": "Richard Doe",
    "MotherName": "Jane Doe"
}

###
DELETE {{MyApp.API_HostAddress}}/api/Student/DeleteStudent/2
Accept: application/json

###
PUT {{MyApp.API_HostAddress}}/api/Student/UpdateStudent/1
Accept: application/json
Content-Type: application/json
{
    "Name": "John Doe",
    "Class": "Bsc.IT",
    "FatherName": "Richard Doe",
    "MotherName": "Jane Doe"
}